//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcommerceDBSitesiEntities : DbContext
    {
        public EcommerceDBSitesiEntities()
            : base("name=EcommerceDBSitesiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<EcommerceUser> EcommerceUsers { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<KullaniciYetki> KullaniciYetkis { get; set; }
        public virtual DbSet<Markalar> Markalars { get; set; }
        public virtual DbSet<UrunDetaylar> UrunDetaylars { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
        public virtual DbSet<UrunlerKategori> UrunlerKategoris { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<UserLogTuru> UserLogTurus { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
    }
}
