//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int SliderID { get; set; }
        public string SliderIsim { get; set; }
        public string SliderAciklama { get; set; }
        public string SliderResim { get; set; }
        public string SliderURL { get; set; }
        public string SliderURLAciklama { get; set; }
        public Nullable<bool> SliderAktiflikDurumu { get; set; }
    }
}
