//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunDetaylar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UrunDetaylar()
        {
            this.Urunlers = new HashSet<Urunler>();
        }
    
        public int UrunDetayID { get; set; }
        public string UrunBoyut { get; set; }
        public string UrunRenk { get; set; }
        public string UrunImage1 { get; set; }
        public string UrunImage2 { get; set; }
        public string UrunImage3 { get; set; }
        public string UrunImage4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urunler> Urunlers { get; set; }
    }
}
