//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int LogID { get; set; }
        public Nullable<int> LogTuruID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string BilgisayarIP { get; set; }
        public string LogAciklama { get; set; }
        public Nullable<int> LogUserID { get; set; }
    
        public virtual UserLogTuru UserLogTuru { get; set; }
    }
}
